include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.2.0/gitlab-ci/docker-support.yml"

run_matrix_build:
  trigger:
    include: .build.yml
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BASE_IMAGE:    [ "alpine", "alpine:3.12" ]
        BUILD_ARGS:    "BASE_IMAGE"
        PIPELINE_MODE: "$PIPELINE_MODE"
