include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.2.0/gitlab-ci/docker-template.yml"

variables:
  UPDATE_CHECK_URLS: 'https://github.com/spacemanspiff2007/sml2mqtt.git'
  DOWNSTREAM_REF: 'master'

build_image:
  trigger:
    include: .build.yml
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BASE_IMAGE:      [ "alpine", "alpine:3.12" ]
        BUILD_ARGS:      "BASE_IMAGE"

publish_image:
  rules:
  - when: never
