run_matrix_build:
  extends: .docker_support:.build_job
  trigger:
    include: .build.yml
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BASE_IMAGE:    [ "alpine", "alpine:3.12" ]
        BUILD_ARGS:    "BASE_IMAGE"
        PIPELINE_MODE: "$PIPELINE_MODE"
