build-services:
  trigger:
    include: .build.yml
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BASE_IMAGE: [ "alpine", "alpine:3.12" ]
        BUILD_ARGS: "MODULE=git+https://github.com/spacemanspiff2007/sml2mqtt.git@c981d1b"
