---
services:
  sml2mqtt:
    image: "ckware/sml2mqtt"
    container_name: sml2mqtt
    restart: unless-stopped
    init: true
    volumes:
      - "./sml2mqtt.yml:/sml2mqtt/config.yml"
    devices:
      - "/dev/ttyUSB0"
